docs: v3.0.0 Update release-notes.md
ibm-cloud-docs/powervs-vpc pull request #1
Opened 2023-10-27 14:25 UTC by surajsbharadwaj

New release notes

2023-10-27 15:44 UTC, SirSpidey requested changes
Hi @surajsbharadwaj. After I reviewed this, I realized that this is in GH. You need to re-create this PR in the internal GHE repo. I'll send you a link in slack. 

This is a complicated release note. 2 important changes are using definition lists `:` and handling the breaking change information.  I have a couple of suggestions. You can also take a look at https://test.cloud.ibm.com/docs/writing?topic=writing-releasenotes

2023-10-27 15:44 UTC, SirSpidey commented on release-notes.md
> +- Upgrade to ibm-sles-15-4-amd64-sap-applications-6 & ibm-redhat-8-6-amd64-sap-applications-4 on intel VSI landing zone for new deployments. Will not affect the previous DA version
```suggestion
Version 3.0.0 of the available
:   Version 3.0.0 of the Power Virtual Server with VPC landing zone deployable architecture is available in the {{site.data.keyword.cloud_notm}} [catalog](/catalog#reference_architecture){: external}.

    - Support all private PowerVS CIDRs in ACL rule;
    - Import any number of PowerVS images , and in parallel.
    - The `clean_default_sg_acl` input is included in the landing zone preset to clean the default sg rule for new deployments.
    - Upgrade to ibm-sles-15-4-amd64-sap-applications-6 & ibm-redhat-8-6-amd64-sap-applications-4 on intel VSI landing zone for new deployments. Will not affect the previous DA version
```
and so on. 

You want to use a definition list here. Here's a suggestion for how i do it with SLZ.

2023-10-27 15:44 UTC, SirSpidey commented on release-notes.md
> +
```suggestion
[Breaking change]{: tag-red}
: Version 3.0.0 includes backward-incompatible changes. Review the following information before you upgrade.
    - Back up the data on the 10.20.10.4 `private-svs-1` VSI in the `/nfs` directory before you upgrade to version 3.0.0.
    - When you upgrade the full-stack solution, the Ansible roles are triggered again, the ACL rules are updated, and the NFS disk will be re-created.
    - Schedule the upgrade. 
        - The new landing zone version re-creates the 1 TB storage disk in a different resource group, so you will experience down time.
        - When you upgrade, the deployable architecture will be down for about 20 minutes, and the Intel VSI will reboot.
   - If you deployed the QuickStart variation, you might want to create another deployable architecture rather than upgrade. The VM and VPC subnets are re-created,, which might affect demos and PoCs, 


```

We don't use warning as a note.

2023-11-03 07:48 UTC, surajsbharadwaj commented
Closing this as @mukesh is working on it on internal repo

2023-11-03 07:48 UTC, closed without merging